### ISSUE TITLE
Update UBQ Farming UI

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uusd.ubq.fi#5]
We changed the flow from manual steps (add liquidity in curve, then lockup LP token in our staking contract) to now “ape in” which handles both in a single transaction. Check `packages/contracts/src/dollar/DirectGovernanceFarmer.sol`

The new UI should be built on top of the related smart contact code changes. The context is available in https://github.com/ubiquity/ubiquity-dollar/issues/243

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4975670/204081820-d5344ff8-c55a-4315-bbfe-8c90ff109ef8.png">

You can upgrade the "Stake Liquidity to Receive UBQ" panel with one that allows users to: 
1. Deposit their uAD+3pool stables (uAD/USDC/USDT/DAI) allow them to select the amount of each of course.
2. Specify the amount of weeks for lockup.
3. Be sure to leave the MAX button functionality in here as well.

Using the `apeIn` method!

**Comment by zugdev** [comment]
I'll take this one.

**Comment by zugdev** [comment]
@0x4007 I don't see an `apeIn` method. Is this issue still valid?

**Comment by rndquu** [comment]
> @0x4007 I don't see an `apeIn` method. Is this issue still valid?

This issue seems to be not relevant because [DirectGovernanceFarmer](https://github.com/ubiquity/ubiquity-dollar/blob/ca74325536c7a9bfaa7209088c30fc7e94e9b02d/packages/contracts/src/dollar/facets/DirectGovernanceFarmerFacet.sol) has been neither deployed nor audited.
