### ISSUE TITLE
Fees and Slippage Tracking + Breakdown

### ISSUE THREAD

**Issue by zugdev** [ubiquity/uusd.ubq.fi#8]
In #4 the optimal UX is having the user know not only the estimated total fees but understand where each fee comes from. This involves integrating CoW Swap quote API, tracking gas costs on-chain, quoting bridge fees with another API. Depending on which bridge we go with we even have to swap into another currency to pay it's fee. It also involves adding / estimating slippage into each of this steps. This would allow for a precise on-ramp cost calculation, ensuring user understand's the output amount of UUSD.

**Comment by 0x4007** [comment]
Whats the problem and whats the deliverable?
